version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running pylint...
      - pylint **/*.py || true  # avoids failing the build due to lint warnings

  build:
    commands:
      - echo Build stage passed.

artifacts:
  files:
    - '**/*'
