# Generated by Django 4.2.20 on 2025-03-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Rent', 'Rent'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Transport', 'Transport'), ('Other', 'Other')], max_length=50, unique=True)),
                ('budget_limit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
