# Generated by Django 4.2.20 on 2025-03-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
