# Generated by Django 4.2.20 on 2025-03-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
